name: Build 32bit

on: [push]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - name: Obtain latest version of the repository
      uses: actions/checkout@v1
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: x86
    - name: Install requirements with PIP
      run: pip install -r requirements.txt
    - name: Install pyinstaller
      run: pip install pyinstaller
    - name: Build Open Shop Channel Downloader
      run: pyinstaller --onefile --icon=oscicon.ico osc-dl.py
    - name: Publish Build Artifacts
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.os }}
        path: dist

  BuildGUI:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - name: Obtain latest version of the repository
      uses: actions/checkout@v1
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: x86
    - name: Install requirements with PIP
      run: pip install -r requirements_GUI.txt
    - name: Install pyinstaller
      run: pip install pyinstaller
    - name: Build Graphical Open Shop Channel Downloader
      run: pyinstaller --onefile --icon=oscicon.ico xosc_dl.py
    - name: Publish Build Artifacts
      uses: actions/upload-artifact@master
      with:
        name: '${{ matrix.os }}-GUI'
        path: dist

